version: '3.8'
services:
  api:
    image: python:3.11
    ports:
      - "8000:8000"
    volumes:
      - ./ml-api:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
